<template>
	<div class="box">
		<h5>
			<span>전체현황</span>
			<b class="fontC">2021-01-20 12:15 기준</b>
		</h5>
		<div class="tableWarp">
			<div class="tableContainer mboard-table">
				<table role="table" class="table b-table">
					<thead role="rowgroup">
						<tr>
							<th rowspan="2">행정구역</th>
							<th rowspan="2">단지</th>
							<th rowspan="2">수용가 수</th>
							<th rowspan="2">검침률</th>
							<th colspan="3">누진단계</th>
						</tr>
						<tr>
							<th>1단계</th>
							<th>2단계</th>
							<th>3단계</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>서울</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>부산</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>대구</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>인천</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>광주</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>대전</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>울산</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>경기</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>강원</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>충북</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>충남</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>전북</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>전남</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>경북</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>경남</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>제주</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
						<tr>
							<td>세종</td>
							<td>15050</td>
							<td>90%</td>
							<td>10</td>
							<td>0</td>
							<td>3</td>
							<td>1</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</template>

<style lang="scss">
@import "~@/assets/scss/table/tableBlack.scss";
</style>
